version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: ago-postgres
    environment:
      POSTGRES_USER: agoAdmin
      POSTGRES_PASSWORD: root@123
      POSTGRES_DB: ago
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
