flamingo.session.cookie.secure: false

commerce:
  product:
    fakeservice:
      enabled: true

postgres:
  user: "postgres"
  password: "supersecurepassword"
  host: "localhost"
  port: 5432
  dbname: "flamingo_db"
  sslmode: "disable"

db:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "agoAdmin"
  password: "root@123"
  database: "ago"
  sslmode: "disable"
